// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kzhrrjcgwfqwtddatkro.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt6aHJyamNnd2Zxd3RkZGF0a3JvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgxMDE3NTEsImV4cCI6MjA2MzY3Nzc1MX0.SGLX17Es3DhpPDkZwaljQPOt2alJxET2jNvDVSb93q0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);